name: Go
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - name: Check out code into the Go module directory
        uses: actions/checkout@v1

      - name: Setup Node.js for use with actions
        uses: actions/setup-node@v1.1.0
        with:
          version: 12.x

      - name: Cache
        uses: actions/cache@v1.0.3
        with:
          path: ~/npm
          key: ${{ runner.os }}-npm

      - name: Install npm packages
        run: |
          cd client
          npm ci

      - name: Build client
        run: |
          cd client
          npm run build:prod

      - name: Set up Go 1.13
        uses: actions/setup-go@v1
        with:
          go-version: 1.13
        id: go

      - name: Generate Statik
        run: |
          cd server
          go get github.com/rakyll/statik
          ~/go/bin/statik --src ../client/dist

      - name: Use Cache
        uses: actions/cache@preview
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('server/go.sum') }}

      - name: Download Modules
        if: steps.cache.outputs.cache-hit != 'true'
        run: |
          cd server
          go mod download

      - name: Build
        run: |
          cd server
          go build -v .

      - name: Test
        run: |
          cd server
          go test
