name: Go
on: [push, pull_request]
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go 1.13
      uses: actions/setup-go@v1
      with:
        go-version: 1.13
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v1
    - name: Get dependencies
      run: |
        cd server
        go get -v -t -d .
        if [ -f Gopkg.toml ]; then
            curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh
            dep ensure
        fi
    - name: Build
      run: |
        cd server
        go build -v .
    - name: Test
      run: |
        cd server
        go test
  danger:
    name: Danger
    runs-on: ubuntu-latest
    steps:
      - name: Setup Go 1.13
        uses: actions/setup-go@v1
        with:
          go-version: 1.13
        id: go
      - name: Install Golint
        run: go get golang.org/x/lint/golint
      - name: install bundler
        run:
          apt-get install bundle
          bundle install
